

# GET http://localhost:2300/followers HTTP/1.1

###
GET http://localhost:2300/followers  HTTP/1.1

###
GET http://localhost:2300/followers/63911ad37524adaa32362b82  HTTP/1.1

###
POST http://localhost:2300/followers     HTTP/1.1
Content-Type: application/json

{
    "name": "The coolest person",
    "subscription": true
}

###
DELETE http://localhost:2300/followers/63911ad37524adaa32362b82  HTTP/1.1

###
PATCH http://localhost:2300/followers/6391cf4da39d7bfaac1614d4
Content-Type: application/json

{
    "name": "Yarn"
}

